jobs:
    include:
        - stage: "Php"
          name: "Php Unit tests"
          language: php
          php: 8.1
          before_script:
              - cd php
              - composer install
          script: php vendor/bin/phpunit
        - script: php vendor/bin/php-cs-fixer fix src --dry-run --diff
          name: "Php CS Fixer"
